#!/bin/sh

# Bash script to plot Cycles outputs
# Author: Yuning Shi (yshi.at.psu.edu)

if [ "$1" != "" ]; then
  project=$1

  echo "Please select the variable to be plotted:"
  echo "1 - Total biomass"
  echo "2 - Grain yield"
  echo "3 - Harvest index"
  echo "4 - Potential transpiration"
  echo "5 - Cumulative Nitrogen stress"
  echo "6 - Water use efficiency"
  echo "7 - Nitrogen concentration"
  echo -n "Select (1--7) > "
  read var
else
  echo "Please specify the project for plotting!"
  exit 1
fi

if [ $var = 1 ]; then
  col=3
  file="output/$1/season.dat"
  var="Total Biomass (Mg ha^{-1})"
elif [ $var = 2 ]; then
  col=5
  file="output/$1/season.dat"
  var="Grain Yield (Mg ha^{-1})"
elif [ $var = 3 ]; then
  col=8
  file="output/$1/season.dat"
  var="Havest Index (Mg Mg^{-1})"
elif [ $var = 4 ]; then
  col=9
  file="output/$1/season.dat"
  var="Potential Transpiration (mm)"
elif [ $var = 5 ]; then
  col=16
  file="output/$1/season.dat"
  var="Cumulative N stress (-)"
elif [ $var = 6 ]; then
  col=101
  file="output/$1/season.dat"
  var="Water Use Efficiency (-)"
elif [ $var = 7 ]; then
  col=102
  file="output/$1/season.dat"
  var="N Concentration (Mg Mg^{-1})"
fi

echo $file
echo $col

gnuplot -e "filename='$file';col='$col';var='$var'" src/tool/plot_output.gpl

exit 0

#gnuplot -e "filename2='output/$2/season.dat';title1='$1';title2='$2'" comparison.plg
#gnuplot -e "filename1='output/$1/season.dat';filename2='output/$2/season.dat';title1='$1';title2='$2'" comparison.plg

